//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cashier.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Cashier extends Employee {
	public void calculateAmount() {
	
	}
	
	public void acceptPayment() {
	
	}
}
