//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Chief.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Chief extends Employee {
	public void acceptOrderMenu() {
	
	}
	
	public void cookMenu() {
	
	}
	
	public void createMenu() {
	
	}
	
	public void modifyMenu() {
	
	}
}
