//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Customer {
	public String customerId;
	public String customerName;
	public Menu select;
	public void selectMenu() {
	
	}
	
	public void orderMenu() {
	
	}
	
	public void payment() {
	
	}
}
