//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Employee.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Employee {
	public String empId;
	public String empName;
	public String empContact;
	public String empAddress;
	public String empPosition;
	public Integer salary;
	public void setEmployee() {
	
	}
	
	public void removeEmployee() {
	
	}
}
