//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Manager.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Manager extends Employee {
	public void manageEmployee() {
	
	}
	
	public void salaryPayrole() {
	
	}
	
	public void manageAnnoucement() {
	
	}
	
	public void manageMenu() {
	
	}
}
