//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Menu {
	public String menuId;
	public Sstring menuName;
	public String category;
	public Integer price;
	public Chief cook;
	public void modifyMenu() {
	
	}
	
	public void deleteMenu() {
	
	}
}
