//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderLine.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class OrderLine {
	public String order;
	public Integer quantity;
	public String menuId;
}
