//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Order {
	public String customerId;
	public String menuId;
	public String menuName;
	public Integer quantity;
	public Integer totalPrice;
	public void addOrderLine() {
	
	}
	
	public void modifyOrderLine() {
	
	}
}
