//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Payment.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Payment {
	public Integer totalPrice;
	public void makePayment() {
	
	}
	
	public void getPayment() {
	
	}
}
