//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Restaurant.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Restaurant {
	public String id;
	public String Name;
	public String Address;
	public String ContactNo;
	public void addNewMenu() {
	
	}
	
	public void isOpen() {
	
	}
	
	public void addNewEmployee() {
	
	}
	
	public void recordOrder() {
	
	}
	
	public void recordEmployeeInfo() {
	
	}
}
