//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Waiter.java
//  @ Date : 9/17/2019
//  @ Author : 
//
//




public class Waiter extends Employee {
	public Integer workHour;
	public void getWorkHour() {
	
	}
	
	public void takeOrder() {
	
	}
	
	public void serviceCustomer() {
	
	}
	
	public void sentOrderToChief() {
	
	}
}
